language: ruby
bundler_args: --without development
sudo: false
rvm: 2.4.2
script: xvfb-run bundle exec rspec spec
addons:
  apt:
    packages:
      - libqtwebkit-dev
      - libqtwebkit4
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: "KMfmShlProJ98WmRWPLAIG07JISf94dWvWFE9Lg7SvbaIiyRCIYEfk9FkCu8dGra4NQvbRHBt63JBqu/eKvzs5hyBENEHZWtYLw3ayR4KUCGqcHV9N0/l9uH2KFg/+FQX0vtcS7KsCNWigZpsLxNrKElnwIPGT48WZWnFf21jN8="
  app: phillip-boksz
  on:
    repo: pboksz/phillip-boksz
notifications:
  email: false
