---
- name: 20th Century (2010)
  stars: 3
- name: 7 Wonders (2010)
  stars: 5
- name: 7 Wonders Duel (2015)
  stars: 5
- name: Agricola (2007)
  stars: 4
- name: Alhambra (2003)
  stars: 4
- name: Apples to Apples (1999)
  stars: 1
- name: 'Ascension: Apprentice Edition (2013)'
  stars: 4
- name: Automobiles (2016)
  stars: 4
- name: 'BANG!: The Walking Dead (2014)'
  stars: 3
- name: Bohnanza (1997)
  stars: 4
- name: 'Boss Monster: The Dungeon Building Card Game (2013)'
  stars: 3
- name: Carcassonne (2000)
  stars: 3
- name: 'Carcassonne: The City (2004)'
  stars: 3
- name: The Castles of Burgundy (2011)
  stars: 4
- name: Catan (1995)
  stars: 4
- name: Caylus (2005)
  stars: 4
- name: La Città (2000)
  stars: 0
- name: Codenames (2015)
  stars: 4
- name: Detroit-Cleveland Grand Prix (1996)
  stars: 4
- name: Dice Brewing (2014)
  stars: 4
- name: Dominion (2008)
  stars: 5
- name: 'Dominion: Intrigue (2009)'
  stars: 5
- name: Dos Rios (2004)
  stars: 3
- name: Dream Home (2016)
  stars: 4
- name: Earthquake (1998)
  stars: 0
- name: Exoplanets (2015)
  stars: 3
- name: Exploding Kittens (2015)
  stars: 3
- name: 'Exploding Kittens: NSFW Deck (2015)'
  stars: 3
- name: 'Firefly: The Game (2013)'
  stars: 4
- name: Galaxy Trucker (2007)
  stars: 4
- name: Guilds of London (2016)
  stars: 5
- name: Guillotine (1998)
  stars: 3
- name: Havana (2009)
  stars: 3
- name: Hive (2001)
  stars: 3
- name: Industry (2010)
  stars: 0
- name: Instinct (1998)
  stars: 0
- name: King of Tokyo (2011)
  stars: 4
- name: Kingdom Builder (2011)
  stars: 3
- name: Kolejka (2011)
  stars: 4
- name: 'Magic: The Gathering (1993)'
  stars: 5
- name: Multiuniversum (2016)
  stars: 4
- name: Munchkin Zombies (2011)
  stars: 2
- name: Not Alone (2016)
  stars: 4
- name: Oh My Goods! (2015)
  stars: 4
- name: Palazzo (2005)
  stars: 3
- name: Pandemic (2008)
  stars: 4
- name: 'Pandemic Legacy: Season 1 (2015)'
  stars: 5
- name: Paris Connection (2010)
  stars: 3
- name: Patchwork (2014)
  stars: 4
- name: Power Grid (2004)
  stars: 4
- name: Puerto Rico (2002)
  stars: 5
- name: Quarantine (2013)
  stars: 4
- name: Race for the Galaxy (2007)
  stars: 5
- name: 'The Resistance: Avalon (2012)'
  stars: 4
- name: 'Robinson Crusoe: Adventures on the Cursed Island (2012)'
  stars: 0
- name: SeaFall (2016)
  stars: 4
- name: Small World Underground (2011)
  stars: 4
- name: Snowdonia (2012)
  stars: 5
- name: Splendor (2014)
  stars: 4
- name: Strajk! Skok do wolności (2013)
  stars: 3
- name: Taboo (1989)
  stars: 3
- name: Terra Mystica (2012)
  stars: 4
- name: Zombie Fluxx (2007)
  stars: 3
