- name: '7 Wonders'
  year: '2010'
  stars: 5
  description: ''

- name: '7 Wonders: Cities'
  year: '2012'
  stars: 5
  description: ''

- name: '7 Wonders: Leaders'
  year: '2011'
  stars: 5
  description: ''

- name: 'Agricola'
  year: '2007'
  stars: 5
  description: ''

- name: 'Bohnanza'
  year: '1997'
  stars: 5
  description: ''

- name: 'Bohnanza: Expansion'
  year: '2010'
  stars: 5
  description: ''

- name: 'Boss Monster: The Dungeon Building Card Game'
  year: '2013'
  stars: 5
  description: ''
